version: 1
index_name: voice-transcripts
required_fields:
  - transcript_id
  - project_id
  - source_path
  - created_at
  - content
  - acl_groups
  - retention_class
optional_fields:
  - speakers
  - topics
  - entities
  - referenced_docs
  - acl_users
  - timestamps
field_types:
  transcript_id: keyword
  project_id: keyword
  source_path: keyword
  created_at: date
  content: text
  speakers: keyword
  topics: keyword
  entities: keyword
  referenced_docs: keyword
  acl_groups: keyword
  acl_users: keyword
  retention_class: keyword
policies:
  raw_audio_indexing_forbidden: true
  evidence_pack_paths_excluded: true
  restricted_class_redaction_supported: true
