gateway_client_secret_or_api_key: 90_days
nextcloud_app_password_or_token: 90_days
db_password: 180_days
webhook_signing_key: 180_days
rotation_evidence_required: true
least_privilege_revalidation_required: true
emergency_rotation_triggers:
  - suspected_compromise
  - staff_change
  - scope_change
