from pathlib import Path
import subprocess
import unittest


class Phase1029ArtifactTests(unittest.TestCase):
    def test_required_sprint_a_files_exist(self):
        required = [
            "docs/02-Ports-Trust-Boundaries/02.20-UFW-Policy-Model.md",
            "docs/03-Security-POPIA/03.20-Secrets-Standard.md",
            "docs/03-Security-POPIA/03.30-Audit-Logging.md",
            "docs/04-Identity-Access-MFA/04.20-Auth-Modes-AD-vs-LocalUsers.md",
            "docs/04-Identity-Access-MFA/04.30-MFA-Policy-Standard.md",
            "docs/04-Identity-Access-MFA/04.40-RoleModel-RBAC-Groups.md",
            "docs/04-Identity-Access-MFA/04.60-SSO-Integration-Matrix-AllApps.md",
            "docs/04-Identity-Access-MFA/04.70-BreakGlass-Recovery.md",
            "docs/10-Backend-Gateway/10.40-Auth-Token-Validation.md",
            "docs/10-Backend-Gateway/10.50-RBAC-Authorization.md",
            "docs/10-Backend-Gateway/10.80-Healthchecks-Watchdog.md",
            "docs/11-Backend-Identity-Provider/11.00-Overview.md",
            "docs/11-Backend-Identity-Provider/11.10-Ports-Boundaries.md",
            "docs/11-Backend-Identity-Provider/11.40-AD-Integration-LDAPS.md",
            "docs/11-Backend-Identity-Provider/11.50-Local-Users-No-Directory.md",
            "docs/11-Backend-Identity-Provider/11.60-MFA-TOTP-WebAuthn-RecoveryCodes.md",
            "docs/11-Backend-Identity-Provider/11.70-Group-to-Role-Mapping.md",
            "docs/20-Frontend-Ingress-UI/20.20-TLS-Internal.md",
            "docs/20-Frontend-Ingress-UI/20.30-UI-SSO-Flow.md",
            "docs/21-Nextcloud/21.00-Overview-RoleInPlatform.md",
            "docs/21-Nextcloud/21.30-Auth-Options-AD-vs-SSO.md",
            "docs/21-Nextcloud/21.35-Permissions-Model-and-Roles.md",
            "docs/21-Nextcloud/21.36-Group-Naming-Convention.md",
            "docs/21-Nextcloud/21.37-Project-Folder-ACL-Blueprint.md",
            "docs/21-Nextcloud/21.45-Audit-Logging-Events.md",
            "docs/21-Nextcloud/21.80-Document-Lifecycle-Workflow-Integration.md",
            "docs/21-Nextcloud/21.81-eSign-Integration-Options.md",
            "docs/30-Search-KnowledgeGraph/30.00-Overview.md",
            "docs/30-Search-KnowledgeGraph/30.10-Sources-and-Connectors.md",
            "docs/30-Search-KnowledgeGraph/30.15-ACL-and-Permissions-Inheritance.md",
            "docs/30-Search-KnowledgeGraph/30.70-Retention-Privacy-Controls.md",
            "docs/30-Search-KnowledgeGraph/30.90-Voice-Transcript-Indexing-and-Graph-Linking.md",
            "docs/40-Automation-n8n/40.00-Overview.md",
            "docs/40-Automation-n8n/40.10-Ports-Boundaries.md",
            "docs/40-Automation-n8n/40.20-SSO-MFA-Policy.md",
            "docs/40-Automation-n8n/40.30-Secrets-and-Credentials-Policy.md",
            "docs/40-Automation-n8n/40.50-Backup-Restore.md",
            "docs/40-Automation-n8n/40.60-Verification-Checklist.md",
            "docs/41-Automation-Windmill/41.00-Overview.md",
            "docs/41-Automation-Windmill/41.10-Ports-Boundaries.md",
            "docs/41-Automation-Windmill/41.20-SSO-MFA-Policy.md",
            "docs/41-Automation-Windmill/41.30-Secrets-Policy.md",
            "docs/41-Automation-Windmill/41.50-Backup-Restore.md",
            "docs/41-Automation-Windmill/41.60-Verification-Checklist.md",
            "docs/60-Voice-Transcription/60.00-Overview.md",
            "docs/60-Voice-Transcription/60.10-Architecture-DataFlow.md",
            "docs/60-Voice-Transcription/60.30-Storage-Model-Nextcloud-Folders.md",
            "docs/60-Voice-Transcription/60.40-RBAC-Access-Controls.md",
            "docs/60-Voice-Transcription/60.50-Retention-Policy-Voice-Transcripts.md",
            "docs/60-Voice-Transcription/60.60-Audit-Events-Transcription.md",
            "docs/60-Voice-Transcription/60.70-Search-Indexing-Integration.md",
            "docs/70-Document-Workflow-eSign/70.10-Approval-Chain-Model.md",
            "docs/70-Document-Workflow-eSign/70.11-Approve-Reject-Actions-and-Escalations.md",
            "docs/70-Document-Workflow-eSign/70.30-Signature-Standards-Verification.md",
            "docs/70-Document-Workflow-eSign/70.40-Document-Versioning-and-Hashing.md",
            "docs/70-Document-Workflow-eSign/70.50-Audit-Trail-and-Evidence-Pack.md",
            "docs/71-Notifications-Mail/71.10-Mail-Architecture-LAN-Only.md",
            "docs/71-Notifications-Mail/71.15-Actionable-Email-Approve-Reject-Links.md",
            "docs/71-Notifications-Mail/71.40-Audit-Logging-MailEvents.md",
            "docs/71-Notifications-Mail/71.50-Retention-MailEvidence.md",
            "docs/50-Monitoring-Logging/50.30-Audit-Events-and-Retention.md",
            "infrastructure/firewall/README.md",
            "infrastructure/firewall/vars.env.example",
            "infrastructure/firewall/apply-ufw-frontend.sh",
            "infrastructure/firewall/apply-ufw-backend.sh",
            "infrastructure/firewall/verify-ufw.sh",
            "infrastructure/audit-logging/README.md",
            "infrastructure/audit-logging/03.30-audit-inputs.env.example",
            "infrastructure/audit-logging/03.30-audit-sources.yml",
            "infrastructure/audit-logging/03.30-audit-verify.sh",
            "infrastructure/audit-logging/03.30-review-routine.template.md",
            "infrastructure/audit-logging/03.30-evidence-checklist.md",
            "infrastructure/keycloak/11.10-idp-ports-boundaries.yml",
            "infrastructure/keycloak/11.10-idp-ports-verify.sh",
            "infrastructure/keycloak/11.40-ad-ldaps-inputs.env.example",
            "infrastructure/keycloak/11.40-ad-ldaps.yaml.example",
            "infrastructure/keycloak/11.40-group-mapping.yaml.example",
            "infrastructure/keycloak/11.40-ad-ldaps-verify.sh",
            "infrastructure/keycloak/11.40-evidence-checklist.md",
            "infrastructure/keycloak/11.50-local-users-inputs.env.example",
            "infrastructure/keycloak/11.50-local-users.yaml.example",
            "infrastructure/keycloak/11.50-local-users-verify.sh",
            "infrastructure/keycloak/11.50-local-users-access-review.template.md",
            "infrastructure/keycloak/11.50-evidence-checklist.md",
            "infrastructure/keycloak/11.60-mfa-policy.yaml.example",
            "infrastructure/keycloak/11.60-mfa-enrollment-checklist.template.md",
            "infrastructure/keycloak/11.60-mfa-verify.sh",
            "infrastructure/keycloak/11.60-evidence-checklist.md",
            "infrastructure/keycloak/11.70-claims-standard.yaml.example",
            "infrastructure/keycloak/11.70-group-taxonomy.yaml.example",
            "infrastructure/keycloak/11.70-project-codes.yaml.example",
            "infrastructure/keycloak/11.70-group-role-mapping-verify.sh",
            "infrastructure/gateway/20.20-tls-inputs.env.example",
            "infrastructure/gateway/20.20-ui-san.cnf.example",
            "infrastructure/gateway/20.20-tls-verify.sh",
            "infrastructure/gateway/20.20-evidence-checklist.md",
            "infrastructure/gateway/20.30-ui-sso-inputs.env.example",
            "infrastructure/gateway/20.30-ui-sso-flow-checklist.template.md",
            "infrastructure/gateway/20.30-ui-sso-verify.sh",
            "infrastructure/gateway/20.30-evidence-checklist.md",
            "infrastructure/gateway/10.40-oidc-validation.yaml.example",
            "infrastructure/gateway/10.40-gateway-env.template",
            "infrastructure/gateway/10.40-token-validation-verify.sh",
            "infrastructure/gateway/10.50-rbac.yaml.example",
            "infrastructure/gateway/10.50-projects.yaml.example",
            "infrastructure/gateway/10.50-policy-matrix.yaml.example",
            "infrastructure/gateway/10.50-rbac-verify.sh",
            "infrastructure/gateway/10.80-healthcheck.sh",
            "infrastructure/gateway/10.80-deps-check.sh",
            "infrastructure/gateway/10.80-watchdog-log-summary.sh",
            "infrastructure/gateway/10.80-compose-healthcheck.template.yml",
            "infrastructure/gateway/10.80-systemd-watchdog.service.template",
            "infrastructure/gateway/10.80-health-watchdog-verify.sh",
            "infrastructure/gateway/04.60-sso-integration-matrix.yml",
            "infrastructure/gateway/04.60-sso-integration-verify.sh",
            "infrastructure/keycloak/04.40-rbac-groups-matrix.yml",
            "infrastructure/keycloak/04.40-rbac-groups-verify.sh",
            "infrastructure/keycloak/04.20-auth-modes-decision.yml",
            "infrastructure/keycloak/04.20-auth-modes-verify.sh",
            "infrastructure/nextcloud/README.md",
            "infrastructure/nextcloud/21.00-overview-inputs.env.example",
            "infrastructure/nextcloud/21.00-overview-verify.sh",
            "infrastructure/nextcloud/21.30-auth-decision-matrix.yml",
            "infrastructure/nextcloud/21.30-auth-options-inputs.env.example",
            "infrastructure/nextcloud/21.30-auth-options-verify.sh",
            "infrastructure/nextcloud/21.35-role-catalog.yml",
            "infrastructure/nextcloud/21.35-permission-matrix.csv",
            "infrastructure/nextcloud/21.35-permissions-inputs.env.example",
            "infrastructure/nextcloud/21.35-permissions-verify.sh",
            "infrastructure/nextcloud/21.36-group-taxonomy.yml",
            "infrastructure/nextcloud/21.36-project-code-register.template.csv",
            "infrastructure/nextcloud/21.36-group-naming-inputs.env.example",
            "infrastructure/nextcloud/21.36-group-naming-verify.sh",
            "infrastructure/nextcloud/21.37-project-folder-template.txt",
            "infrastructure/nextcloud/21.37-acl-blueprint.csv",
            "infrastructure/nextcloud/21.37-onboarding-checklist.template.md",
            "infrastructure/nextcloud/21.37-project-acl-inputs.env.example",
            "infrastructure/nextcloud/21.37-project-acl-verify.sh",
            "infrastructure/nextcloud/21.45-audit-event-taxonomy.yml",
            "infrastructure/nextcloud/21.45-audit-inputs.env.example",
            "infrastructure/nextcloud/21.45-evidence-pack.template.md",
            "infrastructure/nextcloud/21.45-audit-verify.sh",
            "infrastructure/nextcloud/21.80-lifecycle-folder-template.txt",
            "infrastructure/nextcloud/21.80-lifecycle-state-model.yml",
            "infrastructure/nextcloud/21.80-evidence-pack-manifest.template.json",
            "infrastructure/nextcloud/21.80-lifecycle-inputs.env.example",
            "infrastructure/nextcloud/21.80-lifecycle-workflow-verify.sh",
            "infrastructure/nextcloud/21.81-esign-options-matrix.yml",
            "infrastructure/nextcloud/21.81-esign-inputs.env.example",
            "infrastructure/nextcloud/21.81-signature-verification-checklist.template.md",
            "infrastructure/nextcloud/21.81-esign-options-verify.sh",
            "infrastructure/search-graph/README.md",
            "infrastructure/search-graph/30.00-overview-inputs.env.example",
            "infrastructure/search-graph/30.00-source-catalog.template.yml",
            "infrastructure/search-graph/30.00-acl-enforcement-policy.yml",
            "infrastructure/search-graph/30.00-overview-verify.sh",
            "infrastructure/search-graph/30.10-connector-inventory.template.yml",
            "infrastructure/search-graph/30.10-connector-onboarding-checklist.template.md",
            "infrastructure/search-graph/30.10-connector-inputs.env.example",
            "infrastructure/search-graph/30.10-connector-verify.sh",
            "infrastructure/search-graph/30.15-acl-enforcement-policy.yml",
            "infrastructure/search-graph/30.15-principal-mapping.template.yml",
            "infrastructure/search-graph/30.15-acl-regression-checklist.template.md",
            "infrastructure/search-graph/30.15-acl-inputs.env.example",
            "infrastructure/search-graph/30.15-acl-inheritance-verify.sh",
            "infrastructure/search-graph/30.70-retention-policy.yml",
            "infrastructure/search-graph/30.70-content-class-retention-matrix.csv",
            "infrastructure/search-graph/30.70-deletion-propagation-sla.yml",
            "infrastructure/search-graph/30.70-privacy-regression-checklist.template.md",
            "infrastructure/search-graph/30.70-retention-inputs.env.example",
            "infrastructure/search-graph/30.70-retention-privacy-verify.sh",
            "infrastructure/search-graph/30.90-transcript-index-schema.yml",
            "infrastructure/search-graph/30.90-graph-linking-rules.yml",
            "infrastructure/search-graph/30.90-voice-linking-inputs.env.example",
            "infrastructure/search-graph/30.90-voice-linking-verification-checklist.template.md",
            "infrastructure/search-graph/30.90-voice-transcript-linking-verify.sh",
            "infrastructure/voice-transcription/README.md",
            "infrastructure/voice-transcription/60.00-overview-inputs.env.example",
            "infrastructure/voice-transcription/60.00-role-map.yml",
            "infrastructure/voice-transcription/60.00-data-lifecycle.template.yml",
            "infrastructure/voice-transcription/60.00-overview-verify.sh",
            "infrastructure/voice-transcription/60.10-topology-options.yml",
            "infrastructure/voice-transcription/60.10-trust-boundaries.yml",
            "infrastructure/voice-transcription/60.10-data-flows.template.md",
            "infrastructure/voice-transcription/60.10-failure-modes.csv",
            "infrastructure/voice-transcription/60.10-architecture-inputs.env.example",
            "infrastructure/voice-transcription/60.10-architecture-verify.sh",
            "infrastructure/voice-transcription/60.30-folder-blueprint.txt",
            "infrastructure/voice-transcription/60.30-state-transitions.yml",
            "infrastructure/voice-transcription/60.30-metadata-schema.template.json",
            "infrastructure/voice-transcription/60.30-naming-convention.md",
            "infrastructure/voice-transcription/60.30-storage-inputs.env.example",
            "infrastructure/voice-transcription/60.30-storage-verify.sh",
            "infrastructure/voice-transcription/60.40-role-permission-matrix.csv",
            "infrastructure/voice-transcription/60.40-group-mapping.template.yml",
            "infrastructure/voice-transcription/60.40-nextcloud-acl-map.csv",
            "infrastructure/voice-transcription/60.40-api-authz-rules.yml",
            "infrastructure/voice-transcription/60.40-rbac-inputs.env.example",
            "infrastructure/voice-transcription/60.40-rbac-verify.sh",
            "infrastructure/voice-transcription/60.50-retention-classes.yml",
            "infrastructure/voice-transcription/60.50-retention-decision-matrix.csv",
            "infrastructure/voice-transcription/60.50-legal-hold-controls.yml",
            "infrastructure/voice-transcription/60.50-purge-evidence.template.json",
            "infrastructure/voice-transcription/60.50-retention-inputs.env.example",
            "infrastructure/voice-transcription/60.50-retention-verify.sh",
            "infrastructure/voice-transcription/60.60-audit-event-taxonomy.yml",
            "infrastructure/voice-transcription/60.60-audit-mandatory-fields.yml",
            "infrastructure/voice-transcription/60.60-alert-rules.yml",
            "infrastructure/voice-transcription/60.60-audit-inputs.env.example",
            "infrastructure/voice-transcription/60.60-audit-verify.sh",
            "infrastructure/voice-transcription/60.70-index-eligibility-rules.yml",
            "infrastructure/voice-transcription/60.70-index-field-mapping.csv",
            "infrastructure/voice-transcription/60.70-search-acl-policy.yml",
            "infrastructure/voice-transcription/60.70-graph-linking-policy.yml",
            "infrastructure/voice-transcription/60.70-search-indexing-inputs.env.example",
            "infrastructure/voice-transcription/60.70-search-indexing-verify.sh",
            "infrastructure/workflow-esign/README.md",
            "infrastructure/workflow-esign/70.10-approval-chain-template.yml",
            "infrastructure/workflow-esign/70.10-routing-inputs-schema.yml",
            "infrastructure/workflow-esign/70.10-delegation-policy.yml",
            "infrastructure/workflow-esign/70.10-approval-chain-inputs.env.example",
            "infrastructure/workflow-esign/70.10-approval-chain-verify.sh",
            "infrastructure/workflow-esign/70.11-action-semantics.yml",
            "infrastructure/workflow-esign/70.11-sla-escalation-policy.yml",
            "infrastructure/workflow-esign/70.11-email-action-policy.yml",
            "infrastructure/workflow-esign/70.11-approve-reject-inputs.env.example",
            "infrastructure/workflow-esign/70.11-approve-reject-verify.sh",
            "infrastructure/workflow-esign/70.30-signature-tier-policy.yml",
            "infrastructure/workflow-esign/70.30-receipt-schema.template.json",
            "infrastructure/workflow-esign/70.30-key-rotation-policy.yml",
            "infrastructure/workflow-esign/70.30-signature-verification-checklist.template.md",
            "infrastructure/workflow-esign/70.30-signature-inputs.env.example",
            "infrastructure/workflow-esign/70.30-signature-verify.sh",
            "infrastructure/workflow-esign/70.40-versioning-policy.yml",
            "infrastructure/workflow-esign/70.40-hash-standard.yml",
            "infrastructure/workflow-esign/70.40-version-evidence-summary.template.json",
            "infrastructure/workflow-esign/70.40-versioning-inputs.env.example",
            "infrastructure/workflow-esign/70.40-versioning-hashing-verify.sh",
            "infrastructure/workflow-esign/70.50-evidence-pack-structure.template.txt",
            "infrastructure/workflow-esign/70.50-audit-event-minimums.yml",
            "infrastructure/workflow-esign/70.50-evidence-access-policy.yml",
            "infrastructure/workflow-esign/70.50-audit-export.template.json",
            "infrastructure/workflow-esign/70.50-evidence-pack-inputs.env.example",
            "infrastructure/workflow-esign/70.50-audit-evidence-verify.sh",
            "infrastructure/notifications-mail/README.md",
            "infrastructure/notifications-mail/71.10-mail-routing-models.yml",
            "infrastructure/notifications-mail/71.10-smtp-relay-security-baseline.yml",
            "infrastructure/notifications-mail/71.10-mail-flow-checklist.template.md",
            "infrastructure/notifications-mail/71.10-mail-architecture-inputs.env.example",
            "infrastructure/notifications-mail/71.10-mail-architecture-verify.sh",
            "infrastructure/notifications-mail/71.15-action-token-policy.yml",
            "infrastructure/notifications-mail/71.15-email-template-fields.yml",
            "infrastructure/notifications-mail/71.15-actionable-email-inputs.env.example",
            "infrastructure/notifications-mail/71.15-action-flow-checklist.template.md",
            "infrastructure/notifications-mail/71.15-actionable-email-verify.sh",
            "infrastructure/notifications-mail/71.40-mail-audit-event-taxonomy.yml",
            "infrastructure/notifications-mail/71.40-mail-audit-common-fields.yml",
            "infrastructure/notifications-mail/71.40-mail-audit-retention-policy.yml",
            "infrastructure/notifications-mail/71.40-mail-audit-verification-checklist.template.md",
            "infrastructure/notifications-mail/71.40-mail-audit-inputs.env.example",
            "infrastructure/notifications-mail/71.40-mail-audit-verify.sh",
            "infrastructure/notifications-mail/71.50-mail-evidence-retention-schedule.yml",
            "infrastructure/notifications-mail/71.50-mail-evidence-legal-hold-policy.yml",
            "infrastructure/notifications-mail/71.50-mail-evidence-purge-controls.yml",
            "infrastructure/notifications-mail/71.50-mail-evidence-retention-inputs.env.example",
            "infrastructure/notifications-mail/71.50-mail-evidence-verification-checklist.template.md",
            "infrastructure/notifications-mail/71.50-mail-evidence-retention-verify.sh",
            "infrastructure/automation/n8n/README.md",
            "infrastructure/automation/n8n/40.00-n8n-role-boundaries.yml",
            "infrastructure/automation/n8n/40.00-n8n-trust-boundary-matrix.csv",
            "infrastructure/automation/n8n/40.00-n8n-governance-checklist.template.md",
            "infrastructure/automation/n8n/40.00-n8n-inputs.env.example",
            "infrastructure/automation/n8n/40.00-n8n-overview-verify.sh",
            "infrastructure/automation/n8n/40.10-n8n-port-policy.yml",
            "infrastructure/automation/n8n/40.10-n8n-outbound-allowlist.yml",
            "infrastructure/automation/n8n/40.10-n8n-ufw-allowlist.template.csv",
            "infrastructure/automation/n8n/40.10-n8n-boundary-verification-checklist.template.md",
            "infrastructure/automation/n8n/40.10-n8n-boundaries-inputs.env.example",
            "infrastructure/automation/n8n/40.10-n8n-ports-boundaries-verify.sh",
            "infrastructure/automation/n8n/40.20-n8n-identity-modes.yml",
            "infrastructure/automation/n8n/40.20-n8n-mfa-role-policy.csv",
            "infrastructure/automation/n8n/40.20-n8n-rbac-group-mapping.yml",
            "infrastructure/automation/n8n/40.20-n8n-session-policy.yml",
            "infrastructure/automation/n8n/40.20-n8n-sso-mfa-inputs.env.example",
            "infrastructure/automation/n8n/40.20-n8n-sso-mfa-verification-checklist.template.md",
            "infrastructure/automation/n8n/40.20-n8n-sso-mfa-verify.sh",
            "infrastructure/automation/n8n/40.30-n8n-secret-storage-policy.yml",
            "infrastructure/automation/n8n/40.30-n8n-credential-naming-and-ownership.csv",
            "infrastructure/automation/n8n/40.30-n8n-rotation-policy.yml",
            "infrastructure/automation/n8n/40.30-n8n-incident-response-secrets.template.md",
            "infrastructure/automation/n8n/40.30-n8n-secrets-inputs.env.example",
            "infrastructure/automation/n8n/40.30-n8n-secrets-verification-checklist.template.md",
            "infrastructure/automation/n8n/40.30-n8n-secrets-policy-verify.sh",
            "infrastructure/automation/n8n/40.50-n8n-backup-scope.yml",
            "infrastructure/automation/n8n/40.50-n8n-backup-retention-matrix.csv",
            "infrastructure/automation/n8n/40.50-n8n-restore-procedure.template.md",
            "infrastructure/automation/n8n/40.50-n8n-restore-verification-checklist.template.md",
            "infrastructure/automation/n8n/40.50-n8n-backup-restore-inputs.env.example",
            "infrastructure/automation/n8n/40.50-n8n-backup-restore-verify.sh",
            "infrastructure/automation/n8n/40.60-n8n-verification-matrix.csv",
            "infrastructure/automation/n8n/40.60-n8n-verification-checklist.template.md",
            "infrastructure/automation/n8n/40.60-n8n-evidence-pack.template.md",
            "infrastructure/automation/n8n/40.60-n8n-verification-inputs.env.example",
            "infrastructure/automation/n8n/40.60-n8n-verification-verify.sh",
            "infrastructure/automation/windmill/README.md",
            "infrastructure/automation/windmill/41.00-windmill-role-boundaries.yml",
            "infrastructure/automation/windmill/41.00-windmill-vs-n8n-decision-matrix.csv",
            "infrastructure/automation/windmill/41.00-windmill-governance-checklist.template.md",
            "infrastructure/automation/windmill/41.00-windmill-inputs.env.example",
            "infrastructure/automation/windmill/41.00-windmill-overview-verify.sh",
            "infrastructure/automation/windmill/41.10-windmill-port-policy.yml",
            "infrastructure/automation/windmill/41.10-windmill-outbound-allowlist.yml",
            "infrastructure/automation/windmill/41.10-windmill-ufw-allowlist.template.csv",
            "infrastructure/automation/windmill/41.10-windmill-boundary-verification-checklist.template.md",
            "infrastructure/automation/windmill/41.10-windmill-boundaries-inputs.env.example",
            "infrastructure/automation/windmill/41.10-windmill-ports-boundaries-verify.sh",
            "infrastructure/automation/windmill/41.20-windmill-identity-modes.yml",
            "infrastructure/automation/windmill/41.20-windmill-mfa-role-policy.csv",
            "infrastructure/automation/windmill/41.20-windmill-rbac-group-mapping.yml",
            "infrastructure/automation/windmill/41.20-windmill-session-policy.yml",
            "infrastructure/automation/windmill/41.20-windmill-sso-mfa-inputs.env.example",
            "infrastructure/automation/windmill/41.20-windmill-sso-mfa-verification-checklist.template.md",
            "infrastructure/automation/windmill/41.20-windmill-sso-mfa-verify.sh",
            "infrastructure/automation/windmill/41.30-windmill-secret-storage-policy.yml",
            "infrastructure/automation/windmill/41.30-windmill-secret-naming-and-ownership.csv",
            "infrastructure/automation/windmill/41.30-windmill-rotation-policy.yml",
            "infrastructure/automation/windmill/41.30-windmill-incident-response-secrets.template.md",
            "infrastructure/automation/windmill/41.30-windmill-secrets-inputs.env.example",
            "infrastructure/automation/windmill/41.30-windmill-secrets-verification-checklist.template.md",
            "infrastructure/automation/windmill/41.30-windmill-secrets-policy-verify.sh",
            "infrastructure/automation/windmill/41.50-windmill-backup-scope.yml",
            "infrastructure/automation/windmill/41.50-windmill-backup-retention-matrix.csv",
            "infrastructure/automation/windmill/41.50-windmill-restore-procedure.template.md",
            "infrastructure/automation/windmill/41.50-windmill-restore-verification-checklist.template.md",
            "infrastructure/automation/windmill/41.50-windmill-backup-restore-inputs.env.example",
            "infrastructure/automation/windmill/41.50-windmill-backup-restore-verify.sh",
            "infrastructure/automation/windmill/41.60-windmill-verification-matrix.csv",
            "infrastructure/automation/windmill/41.60-windmill-verification-checklist.template.md",
            "infrastructure/automation/windmill/41.60-windmill-evidence-pack.template.md",
            "infrastructure/automation/windmill/41.60-windmill-verification-inputs.env.example",
            "infrastructure/automation/windmill/41.60-windmill-verification-verify.sh",
            "infrastructure/audit-logging/50.30-retention-policy-matrix.yml",
            "infrastructure/audit-logging/50.30-legal-hold-request.template.md",
            "infrastructure/audit-logging/50.30-quarterly-access-review.template.md",
            "infrastructure/audit-logging/50.30-evidence-checklist.md",
            "infrastructure/secrets-standard/README.md",
            "infrastructure/secrets-standard/03.20-stack-inputs.env.example",
            "infrastructure/secrets-standard/03.20-secrets-README.template.txt",
            "infrastructure/secrets-standard/03.20-env.template.example",
            "infrastructure/secrets-standard/03.20-init-stack-layout.sh",
            "infrastructure/secrets-standard/03.20-generate-secret-file.sh",
            "infrastructure/secrets-standard/03.20-verify-secrets-standard.sh",
            "infrastructure/secrets-standard/03.20-evidence-checklist.md",
            "infrastructure/proxmox/networking/bridge-vlan-plan.yml",
            "infrastructure/proxmox/networking/README.md",
            "infrastructure/proxmox/networking/81.50-network-inputs.env.example",
            "infrastructure/proxmox/networking/render-interfaces.sh",
            "infrastructure/proxmox/networking/81.50-network-verify.sh",
            "infrastructure/proxmox/networking/81.50-evidence-checklist.md",
            "infrastructure/proxmox/networking/81.60-verify-inputs.env.example",
            "infrastructure/proxmox/networking/81.60-network-verification.sh",
            "infrastructure/proxmox/networking/81.60-evidence-checklist.md",
            "docs/81-Proxmox-Host/81.60-Network-Verification-Checklist.md",
            "infrastructure/proxmox/storage/README.md",
            "infrastructure/proxmox/storage/storage-plan.yml",
            "infrastructure/proxmox/storage/81.70-storage-decision-inputs.env.example",
            "infrastructure/proxmox/storage/81.70-storage-decision-gate.sh",
            "infrastructure/proxmox/storage/81.80-storage-inputs.env.example",
            "infrastructure/proxmox/storage/81.80-storage-verify.sh",
            "infrastructure/proxmox/storage/81.80-evidence-checklist.md",
            "infrastructure/proxmox/storage/81.90-storage-verify-inputs.env.example",
            "infrastructure/proxmox/storage/81.90-storage-verification.sh",
            "infrastructure/proxmox/storage/81.90-evidence-checklist.md",
            "docs/81-Proxmox-Host/81.70-Storage-Plan-LVM-vs-ZFS.md",
            "docs/81-Proxmox-Host/81.80-Storage-Implementation-StepByStep.md",
            "docs/81-Proxmox-Host/81.90-Storage-Verification-Checklist.md",
            "docs/81-Proxmox-Host/81.100-VM-Blueprints-CPU-RAM-Disk-NIC.md",
            "docs/81-Proxmox-Host/81.110-Ubuntu-24.04-Minimal-Install-DataVM.md",
            "docs/81-Proxmox-Host/81.120-Ubuntu-24.04-Minimal-Install-FrontendVM.md",
            "infrastructure/vm-provisioning/blueprints/vm-blueprints.yml",
            "infrastructure/vm-provisioning/install/README.md",
            "infrastructure/vm-provisioning/install/81.110-ai-data01-inputs.env.example",
            "infrastructure/vm-provisioning/install/81.110-ai-data01-verify.sh",
            "infrastructure/vm-provisioning/install/81.110-netplan-01-netcfg.yaml.example",
            "infrastructure/vm-provisioning/install/81.110-evidence-checklist.md",
            "infrastructure/vm-provisioning/install/81.120-ai-frontend01-inputs.env.example",
            "infrastructure/vm-provisioning/install/81.120-ai-frontend01-verify.sh",
            "infrastructure/vm-provisioning/install/81.120-netplan-01-netcfg.yaml.example",
            "infrastructure/vm-provisioning/install/81.120-evidence-checklist.md",
            "infrastructure/vm-provisioning/hardening/README.md",
            "infrastructure/vm-provisioning/hardening/81.150-hardening-inputs.env.example",
            "infrastructure/vm-provisioning/hardening/base-hardening.sh",
            "infrastructure/vm-provisioning/hardening/verify-hardening.sh",
            "infrastructure/vm-provisioning/hardening/sshd_config.baseline",
            "infrastructure/vm-provisioning/hardening/sshd.local.baseline",
            "infrastructure/vm-provisioning/hardening/50unattended-upgrades.baseline",
            "infrastructure/vm-provisioning/hardening/20auto-upgrades.baseline",
            "infrastructure/vm-provisioning/hardening/81.150-evidence-checklist.md",
            "docs/81-Proxmox-Host/81.150-VM-Base-Hardening-SSH-UFW-UnattendedUpgrades.md",
            "infrastructure/vm-provisioning/access/README.md",
            "infrastructure/vm-provisioning/access/authorized_admin_keys.example",
            "infrastructure/vm-provisioning/access/81.160-access-inputs.env.example",
            "infrastructure/vm-provisioning/access/admin-workstation-inventory.csv",
            "infrastructure/vm-provisioning/access/admin-users-keys.example.csv",
            "infrastructure/vm-provisioning/access/vscode-ssh-config.example",
            "infrastructure/vm-provisioning/access/provision-admin-access.sh",
            "infrastructure/vm-provisioning/access/verify-admin-access.sh",
            "infrastructure/vm-provisioning/access/81.160-evidence-checklist.md",
            "docs/81-Proxmox-Host/81.160-VM-Access-RemoteSSH-Keys-and-AdminWorkstations.md",
            "infrastructure/vm-provisioning/verification/README.md",
            "infrastructure/vm-provisioning/verification/81.190-gate-inputs.env.example",
            "infrastructure/vm-provisioning/verification/81.190-vm-provisioning-gate.sh",
            "infrastructure/vm-provisioning/verification/81.190-evidence-checklist.md",
            "infrastructure/vm-provisioning/verification/verification-gate.md",
            "docs/81-Proxmox-Host/81.190-VM-Provisioning-Verification-Checklist.md",
            "infrastructure/ollama-gpu/README.md",
            "infrastructure/ollama-gpu/82.10-bios-precheck-inputs.env.example",
            "infrastructure/ollama-gpu/82.10-bios-precheck-checklist.md",
            "infrastructure/ollama-gpu/82.10-bios-precheck-gate.sh",
            "infrastructure/ollama-gpu/82.30-hardening-inputs.env.example",
            "infrastructure/ollama-gpu/82.30-hardening-apply.sh",
            "infrastructure/ollama-gpu/82.30-hardening-verify.sh",
            "infrastructure/ollama-gpu/82.30-evidence-checklist.md",
            "infrastructure/ollama-gpu/82.30-sshd_config.baseline",
            "infrastructure/ollama-gpu/82.30-jail.local.baseline",
            "infrastructure/ollama-gpu/82.30-journald-override.conf",
            "infrastructure/ollama-gpu/82.30-50unattended-upgrades.baseline",
            "infrastructure/ollama-gpu/82.30-20auto-upgrades.baseline",
            "infrastructure/ollama-gpu/82.40-ollama-install-inputs.env.example",
            "infrastructure/ollama-gpu/82.40-ollama-override.conf.baseline",
            "infrastructure/ollama-gpu/82.40-ollama-install-apply.sh",
            "infrastructure/ollama-gpu/82.40-ollama-install-verify.sh",
            "infrastructure/ollama-gpu/82.40-evidence-checklist.md",
            "infrastructure/ollama-gpu/82.50-model-allowlist.yaml.example",
            "infrastructure/ollama-gpu/82.50-model-inventory-record.example.json",
            "infrastructure/ollama-gpu/82.50-allowlist-enforced-pull.sh",
            "infrastructure/ollama-gpu/82.50-allowlist-audit.sh",
            "infrastructure/ollama-gpu/82.50-evidence-checklist.md",
            "infrastructure/ollama-gpu/82.60-lan-allowlist-inputs.env.example",
            "infrastructure/ollama-gpu/82.60-lan-allowlist-apply.sh",
            "infrastructure/ollama-gpu/82.60-lan-allowlist-verify.sh",
            "infrastructure/ollama-gpu/82.60-evidence-checklist.md",
            "infrastructure/ollama-gpu/82.80-verification-inputs.env.example",
            "infrastructure/ollama-gpu/82.80-verification-run.sh",
            "infrastructure/ollama-gpu/82.80-evidence-checklist.md",
            "infrastructure/ollama-gpu/82.90-client-rollout-variables.yaml",
            "infrastructure/ollama-gpu/model-allowlist-policy.md",
            "infrastructure/ollama-gpu/pointer-server-profile.yml",
            "infrastructure/prephase/tests/83.00-connectivity-inputs.env.example",
            "infrastructure/prephase/tests/83.00-end-to-end-connectivity.sh",
            "infrastructure/prephase/tests/83.00-evidence-checklist.md",
            "infrastructure/prephase/tests/83.10-dns-inputs.env.example",
            "infrastructure/prephase/tests/83.10-dns-resolution-tests.sh",
            "infrastructure/prephase/tests/83.10-evidence-checklist.md",
            "infrastructure/prephase/tests/83.20-security-smoke-inputs.env.example",
            "infrastructure/prephase/tests/83.20-security-smoke-tests.sh",
            "infrastructure/prephase/tests/83.20-evidence-checklist.md",
            "infrastructure/prephase/tests/83.30-prebootstrap-go-live-gate.md",
            "infrastructure/prephase/tests/83.30-go-live-gate-inputs.env.example",
            "infrastructure/prephase/tests/83.30-go-live-gate-report.sh",
            "docs/82-LLM-Pointer-Server/82.00-Overview-and-RoleInPlatform.md",
            "docs/82-LLM-Pointer-Server/82.10-BIOS-UEFI-GPU-Prechecks.md",
            "docs/82-LLM-Pointer-Server/82.30-Base-Hardening-SSH-UFW-UnattendedUpgrades.md",
            "docs/82-LLM-Pointer-Server/82.40-Ollama-Install-AMD-GPU.md",
            "docs/82-LLM-Pointer-Server/82.50-US-EU-Model-Allowlist-Policy.md",
            "docs/82-LLM-Pointer-Server/82.60-Ollama-LAN-Only-Bind-and-UFW-Allowlist.md",
            "docs/82-LLM-Pointer-Server/82.80-Verification-Checklist.md",
            "docs/82-LLM-Pointer-Server/82.90-Client-Rollout-Variables.md",
            "docs/83-PrePhase-Integration/83.00-EndToEnd-Connectivity-Tests.md",
            "docs/83-PrePhase-Integration/83.10-DNS-and-Naming-Resolution-Tests.md",
            "docs/83-PrePhase-Integration/83.20-Security-Smoke-Tests.md",
            "docs/83-PrePhase-Integration/83.30-PreBootstrap-GoLive-Gate.md",
            "scripts/prephase/verify_artifact_presence.sh",
            "scripts/prephase/verify_audit_logging_artifacts.py",
            "scripts/prephase/verify_auth_modes_artifacts.py",
            "scripts/prephase/verify_break_glass_recovery_artifacts.py",
            "scripts/prephase/verify_rbac_role_model_artifacts.py",
            "scripts/prephase/verify_sso_integration_matrix_artifacts.py",
            "scripts/prephase/verify_mfa_policy_artifacts.py",
            "scripts/prephase/verify_identity_provider_ad_ldaps_artifacts.py",
            "scripts/prephase/verify_identity_provider_local_users_artifacts.py",
            "scripts/prephase/verify_identity_provider_mfa_artifacts.py",
            "scripts/prephase/verify_identity_provider_group_role_mapping_artifacts.py",
            "scripts/prephase/verify_frontend_internal_tls_artifacts.py",
            "scripts/prephase/verify_ui_sso_flow_artifacts.py",
            "scripts/prephase/verify_gateway_token_validation_artifacts.py",
            "scripts/prephase/verify_gateway_rbac_authorization_artifacts.py",
            "scripts/prephase/verify_gateway_healthchecks_watchdog_artifacts.py",
            "scripts/prephase/verify_nextcloud_overview_artifacts.py",
            "scripts/prephase/verify_nextcloud_auth_options_artifacts.py",
            "scripts/prephase/verify_nextcloud_permissions_model_artifacts.py",
            "scripts/prephase/verify_nextcloud_group_naming_artifacts.py",
            "scripts/prephase/verify_nextcloud_project_acl_blueprint_artifacts.py",
            "scripts/prephase/verify_nextcloud_audit_logging_artifacts.py",
            "scripts/prephase/verify_nextcloud_document_lifecycle_workflow_artifacts.py",
            "scripts/prephase/verify_nextcloud_esign_options_artifacts.py",
            "scripts/prephase/verify_search_knowledge_graph_overview_artifacts.py",
            "scripts/prephase/verify_search_knowledge_graph_sources_connectors_artifacts.py",
            "scripts/prephase/verify_search_knowledge_graph_acl_inheritance_artifacts.py",
            "scripts/prephase/verify_search_knowledge_graph_retention_privacy_artifacts.py",
            "scripts/prephase/verify_search_knowledge_graph_voice_transcript_linking_artifacts.py",
            "scripts/prephase/verify_voice_transcription_overview_artifacts.py",
            "scripts/prephase/verify_voice_transcription_architecture_artifacts.py",
            "scripts/prephase/verify_voice_transcription_storage_artifacts.py",
            "scripts/prephase/verify_voice_transcription_rbac_artifacts.py",
            "scripts/prephase/verify_voice_transcription_retention_artifacts.py",
            "scripts/prephase/verify_voice_transcription_audit_events_artifacts.py",
            "scripts/prephase/verify_voice_transcription_search_indexing_artifacts.py",
            "scripts/prephase/verify_workflow_approval_chain_artifacts.py",
            "scripts/prephase/verify_workflow_approve_reject_escalation_artifacts.py",
            "scripts/prephase/verify_workflow_signature_standard_artifacts.py",
            "scripts/prephase/verify_workflow_versioning_hashing_artifacts.py",
            "scripts/prephase/verify_workflow_audit_evidence_pack_artifacts.py",
            "scripts/prephase/verify_notifications_mail_architecture_artifacts.py",
            "scripts/prephase/verify_actionable_email_approve_reject_artifacts.py",
            "scripts/prephase/verify_notifications_mail_audit_logging_artifacts.py",
            "scripts/prephase/verify_notifications_mail_retention_artifacts.py",
            "scripts/prephase/verify_automation_n8n_overview_artifacts.py",
            "scripts/prephase/verify_automation_n8n_ports_boundaries_artifacts.py",
            "scripts/prephase/verify_automation_n8n_sso_mfa_artifacts.py",
            "scripts/prephase/verify_automation_n8n_secrets_policy_artifacts.py",
            "scripts/prephase/verify_automation_n8n_backup_restore_artifacts.py",
            "scripts/prephase/verify_automation_n8n_verification_checklist_artifacts.py",
            "scripts/prephase/verify_automation_windmill_overview_artifacts.py",
            "scripts/prephase/verify_automation_windmill_ports_boundaries_artifacts.py",
            "scripts/prephase/verify_automation_windmill_sso_mfa_artifacts.py",
            "scripts/prephase/verify_automation_windmill_secrets_policy_artifacts.py",
            "scripts/prephase/verify_automation_windmill_backup_restore_artifacts.py",
            "scripts/prephase/verify_automation_windmill_verification_checklist_artifacts.py",
            "scripts/prephase/verify_identity_provider_overview_artifacts.py",
            "scripts/prephase/verify_identity_provider_ports_boundaries_artifacts.py",
            "scripts/prephase/verify_monitoring_audit_retention_artifacts.py",
            "scripts/prephase/verify_secrets_standard_artifacts.py",
            "scripts/prephase/verify_ufw_policy_artifacts.py",
            "scripts/prephase/verify_network_plan.py",
            "scripts/prephase/verify_storage_plan.py",
            "scripts/prephase/verify_vm_blueprints.py",
            "scripts/prephase/verify_vm_install_artifacts.py",
            "scripts/prephase/verify_vm_hardening_artifacts.py",
            "scripts/prephase/verify_vm_access_artifacts.py",
            "scripts/prephase/verify_vm_provisioning_gate_artifacts.py",
            "scripts/prephase/verify_llm_pointer_profile.py",
            "scripts/prephase/verify_llm_bios_precheck_artifacts.py",
            "scripts/prephase/verify_llm_hardening_artifacts.py",
            "scripts/prephase/verify_llm_ollama_install_artifacts.py",
            "scripts/prephase/verify_llm_allowlist_policy_artifacts.py",
            "scripts/prephase/verify_llm_lan_allowlist_artifacts.py",
            "scripts/prephase/verify_llm_verification_checklist_artifacts.py",
            "scripts/prephase/verify_llm_client_rollout_variables_artifacts.py",
            "scripts/prephase/verify_prephase_connectivity_artifacts.py",
            "scripts/prephase/verify_prephase_dns_artifacts.py",
            "scripts/prephase/verify_prephase_security_smoke_artifacts.py",
            "scripts/prephase/verify_prebootstrap_go_live_gate_artifacts.py",
        ]
        for path in required:
            self.assertTrue(Path(path).is_file(), path)

    def test_prephase_verification_scripts_run(self):
        subprocess.run(["bash", "scripts/prephase/verify_artifact_presence.sh"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_audit_logging_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_auth_modes_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_break_glass_recovery_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_rbac_role_model_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_sso_integration_matrix_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_mfa_policy_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_identity_provider_ad_ldaps_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_identity_provider_local_users_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_identity_provider_mfa_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_identity_provider_group_role_mapping_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_frontend_internal_tls_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_ui_sso_flow_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_gateway_token_validation_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_gateway_rbac_authorization_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_gateway_healthchecks_watchdog_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_nextcloud_overview_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_nextcloud_auth_options_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_nextcloud_permissions_model_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_nextcloud_group_naming_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_nextcloud_project_acl_blueprint_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_nextcloud_audit_logging_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_nextcloud_document_lifecycle_workflow_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_nextcloud_esign_options_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_search_knowledge_graph_overview_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_search_knowledge_graph_sources_connectors_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_search_knowledge_graph_acl_inheritance_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_search_knowledge_graph_retention_privacy_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_search_knowledge_graph_voice_transcript_linking_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_voice_transcription_overview_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_voice_transcription_architecture_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_voice_transcription_storage_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_voice_transcription_rbac_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_voice_transcription_retention_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_voice_transcription_audit_events_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_voice_transcription_search_indexing_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_workflow_approval_chain_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_workflow_approve_reject_escalation_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_workflow_signature_standard_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_workflow_versioning_hashing_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_workflow_audit_evidence_pack_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_notifications_mail_architecture_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_actionable_email_approve_reject_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_notifications_mail_audit_logging_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_notifications_mail_retention_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_n8n_overview_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_n8n_ports_boundaries_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_n8n_sso_mfa_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_n8n_secrets_policy_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_n8n_backup_restore_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_n8n_verification_checklist_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_windmill_overview_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_windmill_ports_boundaries_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_windmill_sso_mfa_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_windmill_secrets_policy_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_windmill_backup_restore_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_automation_windmill_verification_checklist_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_identity_provider_overview_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_identity_provider_ports_boundaries_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_monitoring_audit_retention_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_secrets_standard_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_ufw_policy_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_network_plan.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_storage_plan.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_vm_blueprints.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_vm_install_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_vm_hardening_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_vm_access_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_vm_provisioning_gate_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_pointer_profile.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_bios_precheck_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_hardening_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_ollama_install_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_allowlist_policy_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_lan_allowlist_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_verification_checklist_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_client_rollout_variables_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_prephase_connectivity_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_prephase_dns_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_prephase_security_smoke_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_prebootstrap_go_live_gate_artifacts.py"], check=True)
