from pathlib import Path
import subprocess
import unittest


class Phase1029ArtifactTests(unittest.TestCase):
    def test_required_sprint_a_files_exist(self):
        required = [
            "infrastructure/proxmox/networking/bridge-vlan-plan.yml",
            "infrastructure/proxmox/networking/README.md",
            "infrastructure/proxmox/networking/81.50-network-inputs.env.example",
            "infrastructure/proxmox/networking/render-interfaces.sh",
            "infrastructure/proxmox/networking/81.50-network-verify.sh",
            "infrastructure/proxmox/networking/81.50-evidence-checklist.md",
            "infrastructure/proxmox/networking/81.60-verify-inputs.env.example",
            "infrastructure/proxmox/networking/81.60-network-verification.sh",
            "infrastructure/proxmox/networking/81.60-evidence-checklist.md",
            "docs/81-Proxmox-Host/81.60-Network-Verification-Checklist.md",
            "infrastructure/proxmox/storage/README.md",
            "infrastructure/proxmox/storage/storage-plan.yml",
            "infrastructure/proxmox/storage/81.70-storage-decision-inputs.env.example",
            "infrastructure/proxmox/storage/81.70-storage-decision-gate.sh",
            "infrastructure/proxmox/storage/81.80-storage-inputs.env.example",
            "infrastructure/proxmox/storage/81.80-storage-verify.sh",
            "infrastructure/proxmox/storage/81.80-evidence-checklist.md",
            "infrastructure/proxmox/storage/81.90-storage-verify-inputs.env.example",
            "infrastructure/proxmox/storage/81.90-storage-verification.sh",
            "infrastructure/proxmox/storage/81.90-evidence-checklist.md",
            "docs/81-Proxmox-Host/81.70-Storage-Plan-LVM-vs-ZFS.md",
            "docs/81-Proxmox-Host/81.80-Storage-Implementation-StepByStep.md",
            "docs/81-Proxmox-Host/81.90-Storage-Verification-Checklist.md",
            "docs/81-Proxmox-Host/81.100-VM-Blueprints-CPU-RAM-Disk-NIC.md",
            "docs/81-Proxmox-Host/81.110-Ubuntu-24.04-Minimal-Install-DataVM.md",
            "docs/81-Proxmox-Host/81.120-Ubuntu-24.04-Minimal-Install-FrontendVM.md",
            "infrastructure/vm-provisioning/blueprints/vm-blueprints.yml",
            "infrastructure/vm-provisioning/install/README.md",
            "infrastructure/vm-provisioning/install/81.110-ai-data01-inputs.env.example",
            "infrastructure/vm-provisioning/install/81.110-ai-data01-verify.sh",
            "infrastructure/vm-provisioning/install/81.110-netplan-01-netcfg.yaml.example",
            "infrastructure/vm-provisioning/install/81.110-evidence-checklist.md",
            "infrastructure/vm-provisioning/install/81.120-ai-frontend01-inputs.env.example",
            "infrastructure/vm-provisioning/install/81.120-ai-frontend01-verify.sh",
            "infrastructure/vm-provisioning/install/81.120-netplan-01-netcfg.yaml.example",
            "infrastructure/vm-provisioning/install/81.120-evidence-checklist.md",
            "infrastructure/vm-provisioning/hardening/README.md",
            "infrastructure/vm-provisioning/hardening/81.150-hardening-inputs.env.example",
            "infrastructure/vm-provisioning/hardening/base-hardening.sh",
            "infrastructure/vm-provisioning/hardening/verify-hardening.sh",
            "infrastructure/vm-provisioning/hardening/sshd_config.baseline",
            "infrastructure/vm-provisioning/hardening/sshd.local.baseline",
            "infrastructure/vm-provisioning/hardening/50unattended-upgrades.baseline",
            "infrastructure/vm-provisioning/hardening/20auto-upgrades.baseline",
            "infrastructure/vm-provisioning/hardening/81.150-evidence-checklist.md",
            "docs/81-Proxmox-Host/81.150-VM-Base-Hardening-SSH-UFW-UnattendedUpgrades.md",
            "infrastructure/vm-provisioning/access/README.md",
            "infrastructure/vm-provisioning/access/authorized_admin_keys.example",
            "infrastructure/vm-provisioning/access/81.160-access-inputs.env.example",
            "infrastructure/vm-provisioning/access/admin-workstation-inventory.csv",
            "infrastructure/vm-provisioning/access/admin-users-keys.example.csv",
            "infrastructure/vm-provisioning/access/vscode-ssh-config.example",
            "infrastructure/vm-provisioning/access/provision-admin-access.sh",
            "infrastructure/vm-provisioning/access/verify-admin-access.sh",
            "infrastructure/vm-provisioning/access/81.160-evidence-checklist.md",
            "docs/81-Proxmox-Host/81.160-VM-Access-RemoteSSH-Keys-and-AdminWorkstations.md",
            "infrastructure/vm-provisioning/verification/README.md",
            "infrastructure/vm-provisioning/verification/81.190-gate-inputs.env.example",
            "infrastructure/vm-provisioning/verification/81.190-vm-provisioning-gate.sh",
            "infrastructure/vm-provisioning/verification/81.190-evidence-checklist.md",
            "infrastructure/vm-provisioning/verification/verification-gate.md",
            "docs/81-Proxmox-Host/81.190-VM-Provisioning-Verification-Checklist.md",
            "infrastructure/ollama-gpu/README.md",
            "infrastructure/ollama-gpu/82.10-bios-precheck-inputs.env.example",
            "infrastructure/ollama-gpu/82.10-bios-precheck-checklist.md",
            "infrastructure/ollama-gpu/82.10-bios-precheck-gate.sh",
            "infrastructure/ollama-gpu/82.30-hardening-inputs.env.example",
            "infrastructure/ollama-gpu/82.30-hardening-apply.sh",
            "infrastructure/ollama-gpu/82.30-hardening-verify.sh",
            "infrastructure/ollama-gpu/82.30-evidence-checklist.md",
            "infrastructure/ollama-gpu/82.30-sshd_config.baseline",
            "infrastructure/ollama-gpu/82.30-jail.local.baseline",
            "infrastructure/ollama-gpu/82.30-journald-override.conf",
            "infrastructure/ollama-gpu/82.30-50unattended-upgrades.baseline",
            "infrastructure/ollama-gpu/82.30-20auto-upgrades.baseline",
            "infrastructure/ollama-gpu/82.40-ollama-install-inputs.env.example",
            "infrastructure/ollama-gpu/82.40-ollama-override.conf.baseline",
            "infrastructure/ollama-gpu/82.40-ollama-install-apply.sh",
            "infrastructure/ollama-gpu/82.40-ollama-install-verify.sh",
            "infrastructure/ollama-gpu/82.40-evidence-checklist.md",
            "infrastructure/ollama-gpu/82.50-model-allowlist.yaml.example",
            "infrastructure/ollama-gpu/82.50-model-inventory-record.example.json",
            "infrastructure/ollama-gpu/82.50-allowlist-enforced-pull.sh",
            "infrastructure/ollama-gpu/82.50-allowlist-audit.sh",
            "infrastructure/ollama-gpu/82.50-evidence-checklist.md",
            "infrastructure/ollama-gpu/82.60-lan-allowlist-inputs.env.example",
            "infrastructure/ollama-gpu/82.60-lan-allowlist-apply.sh",
            "infrastructure/ollama-gpu/82.60-lan-allowlist-verify.sh",
            "infrastructure/ollama-gpu/82.60-evidence-checklist.md",
            "infrastructure/ollama-gpu/82.80-verification-inputs.env.example",
            "infrastructure/ollama-gpu/82.80-verification-run.sh",
            "infrastructure/ollama-gpu/82.80-evidence-checklist.md",
            "infrastructure/ollama-gpu/82.90-client-rollout-variables.yaml",
            "infrastructure/ollama-gpu/model-allowlist-policy.md",
            "infrastructure/ollama-gpu/pointer-server-profile.yml",
            "infrastructure/prephase/tests/83.00-connectivity-inputs.env.example",
            "infrastructure/prephase/tests/83.00-end-to-end-connectivity.sh",
            "infrastructure/prephase/tests/83.00-evidence-checklist.md",
            "infrastructure/prephase/tests/83.10-dns-inputs.env.example",
            "infrastructure/prephase/tests/83.10-dns-resolution-tests.sh",
            "infrastructure/prephase/tests/83.10-evidence-checklist.md",
            "infrastructure/prephase/tests/83.20-security-smoke-inputs.env.example",
            "infrastructure/prephase/tests/83.20-security-smoke-tests.sh",
            "infrastructure/prephase/tests/83.20-evidence-checklist.md",
            "infrastructure/prephase/tests/83.30-prebootstrap-go-live-gate.md",
            "infrastructure/prephase/tests/83.30-go-live-gate-inputs.env.example",
            "infrastructure/prephase/tests/83.30-go-live-gate-report.sh",
            "docs/82-LLM-Pointer-Server/82.00-Overview-and-RoleInPlatform.md",
            "docs/82-LLM-Pointer-Server/82.10-BIOS-UEFI-GPU-Prechecks.md",
            "docs/82-LLM-Pointer-Server/82.30-Base-Hardening-SSH-UFW-UnattendedUpgrades.md",
            "docs/82-LLM-Pointer-Server/82.40-Ollama-Install-AMD-GPU.md",
            "docs/82-LLM-Pointer-Server/82.50-US-EU-Model-Allowlist-Policy.md",
            "docs/82-LLM-Pointer-Server/82.60-Ollama-LAN-Only-Bind-and-UFW-Allowlist.md",
            "docs/82-LLM-Pointer-Server/82.80-Verification-Checklist.md",
            "docs/82-LLM-Pointer-Server/82.90-Client-Rollout-Variables.md",
            "docs/83-PrePhase-Integration/83.00-EndToEnd-Connectivity-Tests.md",
            "docs/83-PrePhase-Integration/83.10-DNS-and-Naming-Resolution-Tests.md",
            "docs/83-PrePhase-Integration/83.20-Security-Smoke-Tests.md",
            "docs/83-PrePhase-Integration/83.30-PreBootstrap-GoLive-Gate.md",
            "scripts/prephase/verify_artifact_presence.sh",
            "scripts/prephase/verify_network_plan.py",
            "scripts/prephase/verify_storage_plan.py",
            "scripts/prephase/verify_vm_blueprints.py",
            "scripts/prephase/verify_vm_install_artifacts.py",
            "scripts/prephase/verify_vm_hardening_artifacts.py",
            "scripts/prephase/verify_vm_access_artifacts.py",
            "scripts/prephase/verify_vm_provisioning_gate_artifacts.py",
            "scripts/prephase/verify_llm_pointer_profile.py",
            "scripts/prephase/verify_llm_bios_precheck_artifacts.py",
            "scripts/prephase/verify_llm_hardening_artifacts.py",
            "scripts/prephase/verify_llm_ollama_install_artifacts.py",
            "scripts/prephase/verify_llm_allowlist_policy_artifacts.py",
            "scripts/prephase/verify_llm_lan_allowlist_artifacts.py",
            "scripts/prephase/verify_llm_verification_checklist_artifacts.py",
            "scripts/prephase/verify_llm_client_rollout_variables_artifacts.py",
            "scripts/prephase/verify_prephase_connectivity_artifacts.py",
            "scripts/prephase/verify_prephase_dns_artifacts.py",
            "scripts/prephase/verify_prephase_security_smoke_artifacts.py",
            "scripts/prephase/verify_prebootstrap_go_live_gate_artifacts.py",
        ]
        for path in required:
            self.assertTrue(Path(path).is_file(), path)

    def test_prephase_verification_scripts_run(self):
        subprocess.run(["bash", "scripts/prephase/verify_artifact_presence.sh"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_network_plan.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_storage_plan.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_vm_blueprints.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_vm_install_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_vm_hardening_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_vm_access_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_vm_provisioning_gate_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_pointer_profile.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_bios_precheck_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_hardening_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_ollama_install_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_allowlist_policy_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_lan_allowlist_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_verification_checklist_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_llm_client_rollout_variables_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_prephase_connectivity_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_prephase_dns_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_prephase_security_smoke_artifacts.py"], check=True)
        subprocess.run(["python3", "scripts/prephase/verify_prebootstrap_go_live_gate_artifacts.py"], check=True)
